export const TASK_STATUSES = Object.freeze([
  'NEW',
  'ANALYZING',
  'PLAN_READY',
  'IMPLEMENTING',
  'REVIEWING',
  'REVIEW_FAILED',
  'QA',
  'QA_FAILED',
  'SYNC_VALIDATION',
  'SYNC_FAILED',
  'OFFLINE_VALIDATION',
  'PERFORMANCE',
  'PERFORMANCE_FAILED',
  'READY_FOR_INTERNAL_RELEASE',
  'BUILDING',
  'BUILD_FAILED',
  'APPROVED_FOR_INTERNAL_TESTING',
  'DEPLOYING_INTERNAL',
  'INTERNAL_TESTING',
  'INTERNAL_TESTING_PASSED',
  'APPROVED_FOR_PRODUCTION',
  'RELEASED',
  'COMPLETED',
  'BLOCKED'
]);

export const GATE_RESULTS = Object.freeze(['PASS', 'FAIL', 'NOT_REQUIRED', 'BLOCKED']);
export const RISK_LEVELS = Object.freeze(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);

export const LEGAL_TRANSITIONS = Object.freeze({
  NEW: ['ANALYZING', 'BLOCKED'],
  ANALYZING: ['PLAN_READY', 'BLOCKED'],
  PLAN_READY: ['IMPLEMENTING', 'BLOCKED'],
  IMPLEMENTING: ['REVIEWING', 'BLOCKED'],
  REVIEWING: ['REVIEW_FAILED', 'QA', 'BLOCKED'],
  REVIEW_FAILED: ['IMPLEMENTING', 'BLOCKED'],
  QA: ['QA_FAILED', 'SYNC_VALIDATION', 'OFFLINE_VALIDATION', 'PERFORMANCE', 'READY_FOR_INTERNAL_RELEASE', 'COMPLETED', 'BLOCKED'],
  QA_FAILED: ['IMPLEMENTING', 'BLOCKED'],
  SYNC_VALIDATION: ['SYNC_FAILED', 'OFFLINE_VALIDATION', 'PERFORMANCE', 'READY_FOR_INTERNAL_RELEASE', 'COMPLETED', 'BLOCKED'],
  SYNC_FAILED: ['IMPLEMENTING', 'BLOCKED'],
  OFFLINE_VALIDATION: ['PERFORMANCE', 'READY_FOR_INTERNAL_RELEASE', 'COMPLETED', 'BLOCKED'],
  PERFORMANCE: ['PERFORMANCE_FAILED', 'READY_FOR_INTERNAL_RELEASE', 'COMPLETED', 'BLOCKED'],
  PERFORMANCE_FAILED: ['IMPLEMENTING', 'BLOCKED'],
  READY_FOR_INTERNAL_RELEASE: ['BUILDING', 'BLOCKED'],
  BUILDING: ['BUILD_FAILED', 'APPROVED_FOR_INTERNAL_TESTING', 'BLOCKED'],
  BUILD_FAILED: ['IMPLEMENTING', 'READY_FOR_INTERNAL_RELEASE', 'BLOCKED'],
  APPROVED_FOR_INTERNAL_TESTING: ['DEPLOYING_INTERNAL', 'BLOCKED'],
  DEPLOYING_INTERNAL: ['INTERNAL_TESTING', 'BLOCKED'],
  INTERNAL_TESTING: ['INTERNAL_TESTING_PASSED', 'BLOCKED'],
  INTERNAL_TESTING_PASSED: ['APPROVED_FOR_PRODUCTION', 'BLOCKED'],
  APPROVED_FOR_PRODUCTION: ['RELEASED', 'BLOCKED'],
  RELEASED: [],
  COMPLETED: [],
  BLOCKED: ['ANALYZING', 'IMPLEMENTING', 'REVIEWING', 'QA', 'SYNC_VALIDATION', 'OFFLINE_VALIDATION', 'PERFORMANCE', 'READY_FOR_INTERNAL_RELEASE']
});

export const APPROVAL_GATES = new Set([
  'REVIEW_GATE',
  'QA_GATE',
  'SYNC_GATE',
  'OFFLINE_GATE',
  'PERFORMANCE_GATE',
  'BUILD_GATE',
  'INTERNAL_RELEASE_GATE'
]);
