import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  buildNativeZReportContent,
  type NativeZReportInput,
} from "../services/recovery/NativeZReport";
import {
  decodeOriginal,
  encodeOriginal,
} from "../services/recovery/OriginalCodec";
// Frozen outputs from the parent App.tsx, not generated by the extracted implementation.
const fixtures = JSON.parse(
  readFileSync(
    new URL("./fixtures/nativeZReport-parent.json", import.meta.url),
    "utf8",
  ),
);
process.env.TZ = fixtures.timezone;
for (const fixture of fixtures.fixtures)
  test("native complete output matches parent: " + fixture.name, () => {
    const input = decodeOriginal(fixture.input) as NativeZReportInput;
    const before = encodeOriginal(input);
    const actual = buildNativeZReportContent(input);
    assert.equal(encodeOriginal(actual), fixture.expected);
    assert.equal(encodeOriginal(input), before);
    for (const key of [
      "id",
      "sequenceNumber",
      "seriesId",
      "seriesNumber",
      "syncStatus",
      "closedAt",
    ])
      assert.equal(key in actual, false);
  });
test("ordinary Z uses shared producer before series allocation and keeps recovered guard", () => {
  const app = readFileSync(new URL("../App.tsx", import.meta.url), "utf8");
  const block = app.slice(app.indexOf("const handleZReport = async"));
  assert(
    block.indexOf("some(isRecoveredOperation)") <
      block.indexOf("buildNativeZReportContent("),
  );
  assert(
    block.indexOf("buildNativeZReportContent(") <
      block.indexOf("await db.save('internalSequences'"),
  );
  assert(block.includes("...nativeZContent"));
});
