#!/usr/bin/env python3
"""Bounded, explicit target capture. No sales/actions are generated by this tool."""
import argparse,subprocess,json,time
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('command',choices=['start','stop']);p.add_argument('--serial',required=True);p.add_argument('--out',required=True);a=p.parse_args()
adb=Path.home()/'Library/Android/sdk/platform-tools/adb';base=[str(adb),'-s',a.serial];out=Path(a.out);out.mkdir(parents=True,exist_ok=True)
def run(*args):return subprocess.check_output(base+list(args),text=True,timeout=40).strip()
state=out/'capture-state.json'
if a.command=='start':
 assert run('get-state')=='device'
 assert 'versionName=' in run('shell','dumpsys','package','com.clicpos.app')
 config=Path(__file__).with_name('pos.pbtxt');remote='/data/local/tmp/clic-pos-diagnostic.pbtxt';trace='/data/misc/perfetto-traces/clic-pos-'+str(int(time.time()))+'.pftrace'
 run('push',str(config),remote)
 # Start data sources before app restart, so startup and clock synchronization are included.
 output=run('shell','perfetto','--background-wait','--txt','-c',remote,'-o',trace)
 import re
 pid=re.search(r'\b(\d+)\b',output)
 if not pid:raise RuntimeError(output)
 state.write_text(json.dumps({'serial':a.serial,'pid':pid.group(1),'remoteTrace':trace,'started':time.time()},indent=2))
 print(output);print('PERFETTO_STARTED; launch app with --ez pos_diagnostics true, then reproduce >=20 actions')
else:
 s=json.loads(state.read_text());assert s['serial']==a.serial
 run('shell','kill','-TERM',s['pid']);time.sleep(2)
 run('pull',s['remoteTrace'],str(out/'session.pftrace'))
 print(out/'session.pftrace')
