#!/usr/bin/env python3
"""Bounded, explicit target capture. No sales/actions are generated by this tool."""
import argparse,subprocess,json,time,os,signal
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('command',choices=['start','stop']);p.add_argument('--serial',required=True);p.add_argument('--out',required=True);p.add_argument('--system-atrace',action='store_true');a=p.parse_args()
adb=Path.home()/'Library/Android/sdk/platform-tools/adb';base=[str(adb),'-s',a.serial];out=Path(a.out);out.mkdir(parents=True,exist_ok=True)
def run(*args):return subprocess.check_output(base+list(args),text=True,timeout=40).strip()
state=out/'capture-state.json'
if a.command=='start':
 assert run('get-state')=='device'
 assert 'versionName=' in run('shell','dumpsys','package','com.clicpos.app')
 config=Path(__file__).with_name('pos.pbtxt');remote='/data/local/tmp/clic-pos-diagnostic.pbtxt';trace='/data/misc/perfetto-traces/clic-pos-'+str(int(time.time()))+'.pftrace'
 if a.system_atrace:
  # Some Android x86 traced_probes builds acknowledge linux.ftrace but emit no packets.
  text=config.read_text();start=text.index('data_sources { config { name: "linux.ftrace"');end=text.index('data_sources { config { name: "linux.process_stats"',start)
  config=out/'effective.pbtxt';config.write_text(text[:start]+text[end:])
 run('push',str(config),remote)
 # Start data sources before app restart, so startup and clock synchronization are included.
 output=run('shell','perfetto','--background-wait','--txt','-c',remote,'-o',trace)
 import re
 pid=re.search(r'\b(\d+)\b',output)
 if not pid:raise RuntimeError(output)
 if a.system_atrace:run('shell','atrace','--async_start','-b','65536','-a','com.clicpos.app','sched','gfx','view','webview','dalvik','database','binder_driver','input','am','wm')
 log=out/'diagnostic-logcat.txt'
 with log.open('wb') as f:
  stream=subprocess.Popen(base+['logcat','-v','threadtime','-T','1','POS_DIAG_JS:I','POS_DIAG_NATIVE:I','POS_DIAG_FRAME:I','*:S'],stdin=subprocess.DEVNULL,stdout=f,stderr=f,start_new_session=True)
 state.write_text(json.dumps({'serial':a.serial,'pid':pid.group(1),'remoteTrace':trace,'started':time.time(),'systemAtrace':a.system_atrace,'logPid':stream.pid},indent=2))
 print(output);print('PERFETTO_STARTED; launch app with --ez pos_diagnostics true, then reproduce >=20 actions')
else:
 s=json.loads(state.read_text());assert s['serial']==a.serial
 try:run('shell','kill','-TERM',s['pid'])
 except subprocess.CalledProcessError:pass # bounded Perfetto session may already have ended
 try:
  command=subprocess.check_output(['ps','-p',str(s['logPid']),'-o','command='],text=True)
  if str(adb) in command and a.serial in command:os.kill(s['logPid'],signal.SIGTERM)
 except (subprocess.CalledProcessError,ProcessLookupError):pass
 if s.get('systemAtrace'):
  with (out/'system.ctrace').open('wb') as f:subprocess.run(base+['shell','atrace','--async_stop','-z','-b','65536','-a','com.clicpos.app','sched','gfx','view','webview','dalvik','database','binder_driver','input','am','wm'],stdout=f,check=True,timeout=30)
 time.sleep(2)
 run('pull',s['remoteTrace'],str(out/'session.pftrace'))
 print(out/'session.pftrace')
